Arewa Data Science Academy
Deep Learning Cohort1.0
Name: Aminu Ukasha Aliyu
Email: aminu.ukashaaliyu@gmail.com
Title: Week 1 Solution

In [1]:
import torch

In [21]:
#question 2
x = torch.rand(size=(7,7))
print(x)

tensor([[0.3080, 0.8123, 0.8207, 0.9513, 0.1429, 0.3073, 0.4268],
        [0.1861, 0.3188, 0.9439, 0.8315, 0.4132, 0.1832, 0.1247],
        [0.9138, 0.4576, 0.5246, 0.9933, 0.6176, 0.9722, 0.5487],
        [0.1261, 0.0722, 0.2024, 0.0949, 0.1437, 0.5279, 0.2894],
        [0.3511, 0.9626, 0.2178, 0.1194, 0.7033, 0.4481, 0.3840],
        [0.1868, 0.3739, 0.2615, 0.2475, 0.2067, 0.5301, 0.6882],
        [0.1254, 0.3618, 0.3879, 0.0266, 0.2273, 0.3857, 0.5232]])


In [27]:
#question 3
y = torch.rand(size=(1,7))
y_t = torch.transpose(y, 0, 1)
mult_ans = torch.matmul(x,y_t)
mult_ans

tensor([[2.6729],
        [2.0692],
        [3.3890],
        [0.9980],
        [1.7356],
        [1.7436],
        [1.4225]])

In [31]:
#question 4
seed = 0
torch.manual_seed(seed)

x = torch.rand(size=(7,7))
y = torch.rand(size=(1,7))
y_t = torch.transpose(y, 0, 1)
mult_ans = torch.matmul(x,y_t)
mult_ans

tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])

In [35]:
#question 5
torch.cuda.is_available()

False

In [37]:
#question 6
#no gpu

In [41]:
#question 7
x = torch.rand(size=(2,3))
y = torch.rand(size=(2,3))

torch.manual_seed(1234)

In [49]:
#question 7
ans = torch.matmul(x,torch.transpose(y,0,1))
ans

tensor([[0.8921, 1.2261],
        [0.9334, 1.0630]])

In [51]:
#question 8
print('Min:', ans.min())
print('Max:', ans.max())

Min: tensor(0.8921)
Max: tensor(1.2261)


In [61]:
#question 8
print('max index:', torch.argmax(ans))
print('min index:', torch.argmin(ans))

max index: tensor(1)
min index: tensor(0)


In [79]:
torch.manual_seed(7)
x = torch.rand(size=(1, 1, 1, 10))
y = torch.squeeze(x)

print(x)
print(x.shape)
print('\n')
print(y)
print(y.shape)

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]])
torch.Size([1, 1, 1, 10])


tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513])
torch.Size([10])
